name: Build

on:
  push:
    branches: [ main ]
    tags: [v*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Build
        run: pnpm run build
      - uses: EndBug/add-and-commit@v9
        with:
          add: dist/main.user.js
          message: '[CI] Update dist/main.user.js'
      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/main.user.js
          body: ${{ github.event.head_commit.message }}
